# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 19:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feeling', models.CharField(blank=True, max_length=255, null=True)),
                ('need', models.CharField(blank=True, max_length=255, null=True)),
                ('points', models.IntegerField(default=1)),
                ('public', models.BooleanField(default=0)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=10000)),
                ('points', models.IntegerField(default=1)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('checkIn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='log.CheckInEntry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
