# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20161105_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='points',
            field=models.IntegerField(default=500, max_length=100),
            preserve_default=False,
        ),
    ]
