# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.10.3 on 2016-11-05 22:13
=======
# Generated by Django 1.10.1 on 2016-11-05 22:13
>>>>>>> origin/develop
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_badge_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='points',
            field=models.IntegerField(),
        ),
    ]
